USE [master]
GO

CREATE LOGIN [D001] WITH PASSWORD=N'D001', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

CREATE LOGIN [D002] WITH PASSWORD=N'D002', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

CREATE LOGIN [N001] WITH PASSWORD=N'N001', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

CREATE LOGIN [N002] WITH PASSWORD=N'N002', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

CREATE LOGIN [P001] WITH PASSWORD=N'P001', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

CREATE LOGIN [P002] WITH PASSWORD=N'P002', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
